<a href="https://colab.research.google.com/github/pranavlandge36/ml-learning-notebooks/blob/main/Pytorch-Learning/QA_System_Pytorch_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('100_Unique_QA_Dataset.csv')

In [2]:
df

                                             question        answer
0                      What is the capital of France?         Paris
1                     What is the capital of Germany?        Berlin
2                  Who wrote 'To Kill a Mockingbird'?    Harper-Lee
3     What is the largest planet in our solar system?       Jupiter
4      What is the boiling point of water in Celsius?           100
..                                                ...           ...
85                  Who directed the movie 'Titanic'?  JamesCameron
86  Which superhero is also known as the Dark Knight?        Batman
87                     What is the capital of Brazil?      Brasilia
88        Which fruit is known as the king of fruits?         Mango
89       Which country is known for the Eiffel Tower?        France

[90 rows x 2 columns]

In [4]:
df.shape

(90, 2)

In [5]:
## TOKENIZATION
def tokenize(text):
  text=text.lower()
  text= text.replace('?','')
  text= text.replace("'",'')
  return text.split()

In [7]:
tokenize(df['question'][0])

['what', 'is', 'the', 'capital', 'of', 'france']

In [15]:
# VOCABULARY BUILDING
vocab={'<UNK>':0}

def build_vocab(row):
  tok_que = tokenize(row['question'])
  tok_ans = tokenize(row['answer'])

  merged_token= tok_que+tok_ans
  for tokens in merged_token:
    if tokens not in vocab:
      vocab[tokens]=len(vocab)

In [16]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [18]:
len(vocab)

324

In [19]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [25]:
# TEXT TO NUMERICAL INTEGERS/INDICES

def text_to_num(text,vocab):
  indexed_text=[]
  for tokens in tokenize(text):
    if tokens in vocab:
      indexed_text.append(vocab[tokens])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [27]:
text_to_num('What is your name ?',vocab)

[1, 2, 0, 0]

In [28]:
import torch
from torch.utils.data import Dataset, DataLoader

In [29]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab

  def __len__(self):
    return df.shape[0]
  def __getitem__(self, index):
    numerical_question= text_to_num(self.df.iloc[index]['question'],self.vocab)
    numerical_answer= text_to_num(self.df.iloc[index]['answer'],self.vocab)
    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [30]:
dataset=QADataset(df,vocab)

In [32]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [33]:
dataloader= DataLoader(dataset,batch_size=1,shuffle=True)

## SKIPPED PADDING AS BATCH SIZE=1

In [34]:
import torch.nn as nn

In [46]:
class simpleRNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding= nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn=nn.RNN(50,64,batch_first=True)
    self.fc= nn.Linear(64,vocab_size)

  def forward(self,question):
      embedded_question=self.embedding(question)
      hidden, final=self.rnn(embedded_question)
      final_output=final[-1]
      output=self.fc(final_output)
      return output

In [47]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [48]:
learning_rate = 0.001
epochs = 50
model = simpleRNN(len(vocab))
optimizer= torch.optim.Adam(model.parameters(),lr=learning_rate)
criterion= nn.CrossEntropyLoss()

In [49]:
# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 521.215254
Epoch: 2, Loss: 449.399967
Epoch: 3, Loss: 368.375893
Epoch: 4, Loss: 308.977504
Epoch: 5, Loss: 257.741335
Epoch: 6, Loss: 211.096303
Epoch: 7, Loss: 169.310707
Epoch: 8, Loss: 132.152633
Epoch: 9, Loss: 102.721293
Epoch: 10, Loss: 78.538781
Epoch: 11, Loss: 61.231781
Epoch: 12, Loss: 48.213804
Epoch: 13, Loss: 38.660499
Epoch: 14, Loss: 31.103487
Epoch: 15, Loss: 25.644355
Epoch: 16, Loss: 21.329814
Epoch: 17, Loss: 18.300304
Epoch: 18, Loss: 15.952291
Epoch: 19, Loss: 13.939460
Epoch: 20, Loss: 12.281402
Epoch: 21, Loss: 10.919035
Epoch: 22, Loss: 9.773571
Epoch: 23, Loss: 8.696731
Epoch: 24, Loss: 7.924635
Epoch: 25, Loss: 7.078369
Epoch: 26, Loss: 6.457947
Epoch: 27, Loss: 5.615977
Epoch: 28, Loss: 5.049846
Epoch: 29, Loss: 4.589984
Epoch: 30, Loss: 4.227256
Epoch: 31, Loss: 3.870265
Epoch: 32, Loss: 3.510651
Epoch: 33, Loss: 3.219316
Epoch: 34, Loss: 2.978319
Epoch: 35, Loss: 2.753043
Epoch: 36, Loss: 2.547131
Epoch: 37, Loss: 2.368730
Epoch: 38, Loss: 2.185142
Epoch: 39, Loss: 2.038041
Epoch: 40, Loss: 1.895398
Epoch: 41, Loss: 1.768151
Epoch: 42, Loss: 1.655343
Epoch: 43, Loss: 1.552972
Epoch: 44, Loss: 1.451045
Epoch: 45, Loss: 1.363771
Epoch: 46, Loss: 1.278890
Epoch: 47, Loss: 1.202768
Epoch: 48, Loss: 1.131403
Epoch: 49, Loss: 1.064818
Epoch: 50, Loss: 1.002899

In [54]:
def predict(model,question,threshold=0.5):

  numerial_question= text_to_num(question,vocab)

  question_tensor= torch.tensor(numerial_question).unsqueeze(0)

  output= model(question_tensor)
  output_prob= torch.softmax(output,dim=1)
  value, index = torch.max(output_prob, dim=1)
  if value > threshold:
    return print(list(vocab.keys())[index])
  else:
    return ('i dont know')

In [55]:
predict(model,'what is capital of france ?')

paris

In [56]:
predict(model,'ho painted the Mona Lisa?')

leonardo-da-vinci